BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
        
BloggerBlogBundle_nosotros:
    pattern:  /nosotros
    defaults: { _controller: BloggerBlogBundle:Page:nosotros }
    requirements:
        _method:  GET
        
BloggerBlogBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: BloggerBlogBundle:Page:contacto }
    requirements:
        _method:  GET|POST
        
BloggerBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
BloggerBlogBundle_registro:
    pattern:  /registro
    defaults: { _controller: BloggerBlogBundle:Usuario:registro }

BloggerBlogBundle_login:
    pattern:  /login
    defaults: { _controller: BloggerBlogBundle:Usuario:login }

BloggerBlogBundle_check_path:
    pattern:  /check

BloggerBlogBundle_logout:
    pattern:  /logout
    


BloggerBlogBundle_homepage_admin:
    pattern:  /admin
    defaults: { _controller: BloggerBlogBundle:Admin:index }
